"""empty message

Revision ID: 1fb23dfc6934
Revises: 29802dae3bf6
Create Date: 2021-03-11 13:26:13.050943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb23dfc6934'
down_revision = '29802dae3bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
