"""empty message

Revision ID: 3700fd0a8c34
Revises: 387adf9478e6
Create Date: 2021-03-12 11:54:52.343603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3700fd0a8c34'
down_revision = '387adf9478e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso', sa.String(length=64), nullable=True),
    sa.Column('tipo', sa.String(length=64), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_curso'), 'curso', ['curso'], unique=False)
    op.create_index(op.f('ix_curso_duracao'), 'curso', ['duracao'], unique=False)
    op.create_index(op.f('ix_curso_tipo'), 'curso', ['tipo'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=86), nullable=True),
    sa.Column('email', sa.String(length=84), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrelas', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacao_estrelas'), 'avaliacao', ['estrelas'], unique=False)
    op.create_index(op.f('ix_avaliacao_timestamp'), 'avaliacao', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacao_timestamp'), table_name='avaliacao')
    op.drop_index(op.f('ix_avaliacao_estrelas'), table_name='avaliacao')
    op.drop_table('avaliacao')
    op.drop_table('users')
    op.drop_index(op.f('ix_curso_tipo'), table_name='curso')
    op.drop_index(op.f('ix_curso_duracao'), table_name='curso')
    op.drop_index(op.f('ix_curso_curso'), table_name='curso')
    op.drop_table('curso')
    # ### end Alembic commands ###
