"""empty message

Revision ID: 4b6ef492ca26
Revises: 3700fd0a8c34
Create Date: 2021-03-25 12:11:54.043921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6ef492ca26'
down_revision = '3700fd0a8c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('formacao', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professor_data_nascimento'), 'professor', ['data_nascimento'], unique=False)
    op.create_index(op.f('ix_professor_formacao'), 'professor', ['formacao'], unique=False)
    op.create_index(op.f('ix_professor_nome'), 'professor', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professor_nome'), table_name='professor')
    op.drop_index(op.f('ix_professor_formacao'), table_name='professor')
    op.drop_index(op.f('ix_professor_data_nascimento'), table_name='professor')
    op.drop_table('professor')
    # ### end Alembic commands ###
